spring:
  application:
    name: question-service

  datasource:
    url: jdbc:mysql://localhost:3306/question_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081